#!/bin/bash
sudo mkdir -p /opt/app
sudo aws s3 cp s3://<BUCKET_NAME>/auto-scale-app/auto-scale-app /opt/app
sudo chown ec2-user:ec2-user /opt/app
sudo chmod +x /opt/app/auto-scale-app
/opt/app/auto-scale-app &